name: Terragrunt CI

on:
  workflow_call:
    inputs:
      working_directory:
        description: 'Working directory for Terragrunt commands'
        required: true
        type: string

jobs:
  terragrunt-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3

      - name: Terragrunt Format Check
        id: fmt
        run: terragrunt hclfmt --terragrunt-check --all
        continue-on-error: true

      - name: Terragrunt Validate
        id: validate
        run: terragrunt validate --all
        continue-on-error: true

      - name: Terragrunt Plan
        id: plan
        run: terragrunt plan --all --terragrunt-non-interactive
        continue-on-error: true

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const output = `
            #### Terragrunt Results
            - Format: \`${{ steps.fmt.outcome }}\`
            - Validate: \`${{ steps.validate.outcome }}\`
            - Plan: \`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`
            ${{ steps.plan.outputs.stdout }}
            \`\`\`
            
            </details>`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Fail on Error
        if: steps.fmt.outcome == 'failure' || steps.validate.outcome == 'failure' || steps.plan.outcome == 'failure'
        run: exit 1
