name: Terragrunt CD

on:
  workflow_call:
    inputs:
      working_directory:
        description: 'Working directory for Terragrunt commands'
        required: true
        type: string
      github_owner:
        description: 'GitHub organization name'
        required: true
        type: string
      tg_version:
        description: 'Terragrunt version'
        required: false
        type: string
        default: '0.82.3'
      tofu_version:
        description: 'OpenTofu version'
        required: false
        type: string
        default: '1.10.1'
    secrets:
      GH_TOKEN: 
        required: true

jobs:
  terragrunt-cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_OWNER: ${{ inputs.github_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terragrunt Apply
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: ${{ inputs.tg_version }}
          tofu_version: ${{ inputs.tofu_version }}
          tg_dir: ${{ inputs.working_directory }}
          tg_command: 'apply --all'
