name: Terragrunt CI

on:
  workflow_call:
    inputs:
      working_directory:
        description: 'Working directory for Terragrunt commands'
        required: true
        type: string
      tg_version:
        description: 'Terragrunt version'
        required: false
        type: string
        default: '0.82.3'
      tofu_version:
        description: 'OpenTofu version'
        required: false
        type: string
        default: '1.10.1'

jobs:
  terragrunt-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
      GITHUB_OWNER: ${{ github.repository_owner }}
      TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Plugin Cache Dir
        run: mkdir -p $TF_PLUGIN_CACHE_DIR

      - name: Cache Terraform Plugins
        uses: actions/cache@v4
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-plugin-cache-${{ hashFiles('**/versions.tf', '**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-plugin-cache-

      - name: Terragrunt Format Check
        id: fmt
        uses: gruntwork-io/terragrunt-action@v3
        env:
          TF_PLUGIN_CACHE_DIR: ${{ env.TF_PLUGIN_CACHE_DIR }}
        with:
          tg_version: ${{ inputs.tg_version }}
          tofu_version: ${{ inputs.tofu_version }}
          tg_dir: ${{ inputs.working_directory }}
          tg_command: 'hcl format --check --all'

      - name: Terragrunt Validate
        id: validate
        uses: gruntwork-io/terragrunt-action@v3
        env:
          TF_PLUGIN_CACHE_DIR: ${{ env.TF_PLUGIN_CACHE_DIR }}
        with:
          tg_version: ${{ inputs.tg_version }}
          tofu_version: ${{ inputs.tofu_version }}
          tg_dir: ${{ inputs.working_directory }}
          tg_command: 'validate --all'

      - name: Terragrunt Plan
        id: plan
        uses: gruntwork-io/terragrunt-action@v3
        env:
          TF_PLUGIN_CACHE_DIR: ${{ env.TF_PLUGIN_CACHE_DIR }}
        with:
          tg_version: ${{ inputs.tg_version }}
          tofu_version: ${{ inputs.tofu_version }}
          tg_dir: ${{ inputs.working_directory }}
          tg_command: 'plan --all --no-color'
          tg_comment: 1
          github_token: ${{ github.token }}